'use client';

import { useEffect, useMemo, useState } from 'react';

type Request = (path: string, init?: RequestInit) => Promise<any>;
type Question = { id: string; concept_key: string; slug: string; title: string; description: string; prompt: string; version: number; language: string; difficulty: string; question_type: string; active: boolean; published: boolean; question_roles?: { role_name: string }[]; question_skills?: { skill_name: string }[]; };

const emptyForm = { concept_key: '', title: '', description: '', prompt: '', language: 'python', difficulty: 'easy', question_type: 'coding', roles: '', skills: '', runtime_image: 'python:3.12-slim', seed_parameters: '{"seed": 1}', scoring_rules: '{"max_score": 100}', starter_code: '' };
const roles = ['Software Developer', 'Backend Developer', 'Frontend Developer', 'Data Analyst', 'Cybersecurity Analyst'];
const skills = ['Data Structures', 'Algorithms', 'OOP', 'SQL', 'REST APIs', 'Networking', 'Linux', 'Cybersecurity', 'Problem Solving'];

export default function QuestionBank({ request }: { request: Request }) {
  const [items, setItems] = useState<Question[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [filters, setFilters] = useState({ search: '', role: '', language: '', skill: '', difficulty: '', question_type: '', active: '' });
  const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState<Question | null>(null); const [draftEditing, setDraftEditing] = useState<Question | null>(null); const [history, setHistory] = useState<any[]>([]); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const query = useMemo(() => new URLSearchParams({ ...filters, page: String(page), page_size: '12' }).toString(), [filters, page]);

  async function load() { setLoading(true); setError(''); try { const result = await request('/api/tpo/questions?' + query); setItems(result.items || []); setTotal(result.total || 0); } catch (e) { setError(String(e)); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [query]);
  function update(key: string, value: string) { setForm(current => ({ ...current, [key]: value })); }
  function parseJson(value: string, field: string) { try { return JSON.parse(value); } catch { throw new Error(`${field} must be valid JSON`); } }
  function openDraft(question: Question) {
    setDraftEditing(question); setEditing(null); setShowForm(true);
    setForm({ ...emptyForm, concept_key: question.concept_key, title: question.title, description: question.description || '', prompt: question.prompt || '', language: question.language, difficulty: question.difficulty, question_type: question.question_type, roles: question.question_roles?.map(x => x.role_name).join(', ') || '', skills: question.question_skills?.map(x => x.skill_name).join(', ') || '' });
  }
  async function create() {
    setBusy(true); setNotice('');
    try {
      const payload = { ...form, roles: form.roles.split(',').map(x => x.trim()).filter(Boolean), skills: form.skills.split(',').map(x => x.trim()).filter(Boolean), seed_parameters: parseJson(form.seed_parameters, 'Seed parameters'), scoring_rules: parseJson(form.scoring_rules, 'Scoring rules'), language_variants: [{ language: form.language, starter_code: form.starter_code }] };
      if (draftEditing) await request(`/api/tpo/questions/${draftEditing.id}`, { method: 'PATCH', body: JSON.stringify(payload) });
      else await request('/api/tpo/questions', { method: 'POST', body: JSON.stringify(payload) });
      setForm(emptyForm); setDraftEditing(null); setShowForm(false); setNotice(draftEditing ? 'Draft question updated.' : 'Question created as a draft.'); await load();
    } catch (e) { setNotice(String(e)); } finally { setBusy(false); }
  }
  async function makeVersion(question: Question) {
    try { await request(`/api/tpo/questions/${question.id}/version`, { method: 'POST', body: JSON.stringify({ title: `${question.title} · revised` }) }); setNotice(`New draft version created from v${question.version}.`); await load(); } catch (e) { setNotice(String(e)); }
  }
  async function toggle(question: Question) {
    try { await request(`/api/tpo/questions/${question.id}/status`, { method: 'POST', body: JSON.stringify({ active: !question.active }) }); await load(); } catch (e) { setNotice(String(e)); }
  }
  async function showHistory(question: Question) { try { setHistory(await request(`/api/tpo/questions/${question.id}/history`)); setEditing(question); } catch (e) { setNotice(String(e)); } }

  return <section className="question-bank">
    <div className="qb-header"><div><div className="eyebrow">TPO CONTROL ROOM / QUESTION BANK</div><h2>Smart Question Bank</h2><p className="muted">Build reliable assessment signal across role, language, skill, and difficulty.</p></div><button onClick={() => { setShowForm(true); setEditing(null); }}>＋ Create question</button></div>
    <div className="filter-bar"><input placeholder="Search title, concept, description…" value={filters.search} onChange={e => { setPage(1); setFilters({ ...filters, search: e.target.value }); }} /><select value={filters.role} onChange={e => setFilters({ ...filters, role: e.target.value })}><option value="">All roles</option>{roles.map(x => <option key={x}>{x}</option>)}</select><select value={filters.language} onChange={e => setFilters({ ...filters, language: e.target.value })}><option value="">All languages</option><option value="python">Python</option><option value="java">Java</option><option value="cpp">C++</option><option value="javascript">JavaScript</option><option value="c">C</option></select><select value={filters.skill} onChange={e => setFilters({ ...filters, skill: e.target.value })}><option value="">All skills</option>{skills.map(x => <option key={x}>{x}</option>)}</select><select value={filters.difficulty} onChange={e => setFilters({ ...filters, difficulty: e.target.value })}><option value="">All difficulty</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select><select value={filters.active} onChange={e => setFilters({ ...filters, active: e.target.value })}><option value="">Any status</option><option value="true">Active</option><option value="false">Inactive</option></select></div>
    {notice && <div className="notice">{notice}</div>}{error && <div className="error">{error}</div>}
    {showForm && <div className="qb-form"><div className="form-head"><h3>{draftEditing ? 'Edit draft question' : 'Create draft question'}</h3><button className="ghost" onClick={() => { setShowForm(false); setDraftEditing(null); }}>Close</button></div><div className="form-grid"><label>Concept key<input value={form.concept_key} onChange={e => update('concept_key', e.target.value)} placeholder="arrays.first_unique" /></label><label>Title<input value={form.title} onChange={e => update('title', e.target.value)} placeholder="Find the first non-repeating character" /></label><label>Language<select value={form.language} onChange={e => update('language', e.target.value)}><option value="python">Python</option><option value="java">Java</option><option value="cpp">C++</option><option value="javascript">JavaScript</option><option value="c">C</option></select></label><label>Difficulty<select value={form.difficulty} onChange={e => update('difficulty', e.target.value)}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label><label>Question type<select value={form.question_type} onChange={e => update('question_type', e.target.value)}><option value="coding">Coding</option><option value="debugging">Debugging</option><option value="knowledge">Knowledge / MCQ</option><option value="ast">AST Bug Arena</option></select></label><label>Roles <span className="field-hint">comma separated</span><input value={form.roles} onChange={e => update('roles', e.target.value)} placeholder="Backend Developer, Software Developer" /></label><label>Skills <span className="field-hint">comma separated</span><input value={form.skills} onChange={e => update('skills', e.target.value)} placeholder="Data Structures, Algorithms" /></label><label>Runtime image<input value={form.runtime_image} onChange={e => update('runtime_image', e.target.value)} /></label><label className="wide">Description<textarea value={form.description} onChange={e => update('description', e.target.value)} /></label><label className="wide">Prompt<textarea value={form.prompt} onChange={e => update('prompt', e.target.value)} /></label><label>Seed parameters (JSON)<textarea value={form.seed_parameters} onChange={e => update('seed_parameters', e.target.value)} /></label><label>Scoring rules (JSON)<textarea value={form.scoring_rules} onChange={e => update('scoring_rules', e.target.value)} /></label><label className="wide">Starter code<textarea value={form.starter_code} onChange={e => update('starter_code', e.target.value)} /></label></div><button disabled={busy || !form.title || !form.prompt || !form.concept_key} onClick={create}>{busy ? 'Saving…' : draftEditing ? 'Save draft changes' : 'Create draft question'}</button></div>}
    <div className="qb-table-wrap">{loading ? <div className="empty">Loading question bank…</div> : !items.length ? <div className="empty"><strong>No questions match these filters.</strong><br /><span>Try clearing a filter or create your first draft.</span></div> : <table className="qb-table"><thead><tr><th>Question</th><th>Coverage</th><th>Difficulty</th><th>Type</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(question => <tr key={question.id}><td><strong>{question.title}</strong><small>{question.slug} · v{question.version}</small></td><td><div className="badge-row">{question.question_roles?.slice(0, 2).map(x => <span className="badge" key={x.role_name}>{x.role_name}</span>)}<span className="badge dark">{question.language}</span></div><small>{question.question_skills?.map(x => x.skill_name).join(' · ') || 'No skill mapped'}</small></td><td><span className={`difficulty ${question.difficulty}`}>{question.difficulty}</span></td><td>{question.question_type}</td><td><span className={`status ${question.active ? 'active' : 'inactive'}`}>{question.active ? 'Active' : 'Inactive'}{question.published ? ' · Published' : ' · Draft'}</span></td><td><div className="row-actions"><button className="ghost" onClick={() => showHistory(question)}>History</button>{!question.published && <><button className="ghost" onClick={() => openDraft(question)}>Edit draft</button><button className="ghost" onClick={() => toggle(question)}>{question.active ? 'Deactivate' : 'Activate'}</button></>}<button className="ghost" onClick={() => makeVersion(question)}>New version</button></div></td></tr>)}</tbody></table>}</div>
    <div className="pagination"><span>{total ? `${(page - 1) * 12 + 1}–${Math.min(page * 12, total)} of ${total}` : '0 questions'}</span><div><button className="ghost" disabled={page === 1} onClick={() => setPage(page - 1)}>←</button><button className="ghost" disabled={page * 12 >= total} onClick={() => setPage(page + 1)}>→</button></div></div>
    {editing && <div className="history-panel"><div className="form-head"><div><div className="eyebrow">VERSION HISTORY</div><h3>{editing.title}</h3></div><button className="ghost" onClick={() => setEditing(null)}>Close</button></div>{history.map(version => <div className="history-row" key={version.id}><span className="version">v{version.version}</span><span>{version.language} · {version.difficulty}</span><span className={`status ${version.active ? 'active' : 'inactive'}`}>{version.published ? 'Published' : 'Draft'}</span><small>{new Date(version.created_at).toLocaleDateString()}</small></div>)}</div>}
  </section>;
}
